PRINT *, "INGRESA EL IDENTIFICADOR DEL SISTEMA:"
READ (*,*) IDEN

PRINT *, "INGRESA LOS TIPOS DE MODELO Y EXCENTRICIDAD:"
READ (*,*) TMOD, TEXC

PRINT *, "INGRESA EL NUMERO DE PISOS DEL SISTEMA:"
READ (*,*) NP

PRINT *, "INGRESA LOS FACTORES DE REDUCCION EN X Y Y:"
READ (*,*) FREX, FREY

PRINT *, "INGRESA LAS RELACIONES DE ASPECTO Y EXCENTRICIDAD:"º
READ (*,*) RASP, EXC

PRINT *, "INGRESA EL LADO MAYOR DE LA PLANTA, ALTURA DEL ENTREPISO Y CARGA POR M2:"
READ (*,*) B, HI, WUS

PRINT *, "INGRESA EL FACTOR DE ZONA SISMICA Y DE IMPORTANCIA:"
READ (*,*) Z, FI

PRINT *, "INGRESA EL COEFICIENTE DE SITIO Y PERIODO:"
READ (*,*) S, CT

PRINT *, "INGRESA EL ARCHIVO DE ACELERACIONES EN X:"
READ (*,*) ACEX

PRINT *, "INGRESA EL NUMERO DE REGISTROS EN X:"
READ (*,*) NAX

PRINT *, "INGRESA EL FACTOR DE ESCALA E INCREMENTO DE TIEMPO EN X:"
READ (*,*) FEX, DTX

PRINT *, "INGRESA EL ARCHIVO DE ACELERACIONES EN Y:"
READ (*,*) ACEY


READ(1, *) IDEN;                 WRITE(*, 10) IDEN
READ(1, *) TMOD, TEXC;           WRITE(*, 20) TMOD, TEXC
READ(1, *) NP, FREX, FREY;       WRITE(*, 30) NP; WRITE(*, 40) FREX, FREY
READ(1, *) RASP, B, EXC, HI, WUS;WRITE(*, 50) RASP, EXC; WRITE(*, 60) B, HI, WUS
READ(1, *) Z, FI, S, CT;         WRITE(*, 70) Z, FI; WRITE(*, 80) S, CT
READ(1, *) ACEX;                 WRITE(*, 90) ACEX
READ(1, *) NAX;                  WRITE(*, 100) NAX
READ(1, *) FEX, DTX;             WRITE(*, 110) FEX, DTY

10 FORMAT(' ', 'IDENTIFICADOR DEL SISTEMA:', T63, A20)
20 FORMAT(' ', 'TIPOS MODELO Y EXCENTRICIDAD:', T63, I2, 3X, I2)
30 FORMAT(' ', 'PISOS DEL SISTEMA:', T63, I2)
40 FORMAT(' ', 'FACTORES REDUCCIÓN DIR X E Y:', T63, I2, 3X, I2)
50 FORMAT(' ', 'RELACIONES DE ASPECTO Y EXCENTRICIDAD:', T62, 2F6.2)
60 FORMAT(' ', 'LADO MAYOR PLANTA, ALTURA ENTREPISO Y CARGA POR M2:', F5.2, F6.2, F6.2)
70 FORMAT(' ', 'FACTOR ZONA SÍSMICA Y DE IMPORTANCIA:', 2F6.2)
80 FORMAT(' ', 'COEFICIENTE DE SITIO Y PERIODO:', 2F6.2)
90 FORMAT(' ', 'ARCHIVO ACELERACIONES EN X:', A20)
100 FORMAT(' ', 'NUM. REGISTROS EN X:', I4)
110 FORMAT(' ', 'FACTOR DE ESCALA E INCREMENTO DE TIEMPO EN X:', 2F8.2)
130 FORMAT(' ', 'ARREGLO ACELERACIONES EN Y:', A20)
140 FORMAT(' ', 'NUM REGISTROS EN Y:', I4)
150 FORMAT(' ', 'FACTOR DE ESCALA E INCREMENTO DE TIEMPO EN Y:', 2F8.2)
200 FORMAT(' ', 'ERROR AL ABRIR ARCHIVO ACELERACIONES X, IOSTAT=', I6)
210 FORMAT(' ', 'ERROR AL ABRIR ARCHIVO ACELERACIONES Y, IOSTAT=', I6)
220 FORMAT(' ', 'ERROR AL ABRIR ARCHIVO DATOS DEL SISTEMA, IOSTAT=', I6)
